---
- hosts: all
  vars_files:
     - "common_vars.yml"
  tasks:
     - name: install devstack pre-reqs and wireshark
       sudo: true
       apt: name={{item}} state=present
       with_items:
       - git
       - emacs
       - xbase-clients
       - wireshark

     - name: grab devstack
       git: repo={{ devstack_repository }} version={{ devstack_repo_version }} dest=/home/vagrant/devstack update=no

     - name: grab networking_ovn
       git: repo={{ networking_ovn_repository }} version={{ networking_ovn_repo_version }} dest=/home/vagrant/networking_ovn update=no

- hosts: devstack-control
  tasks:
     - name: create initial local.conf
       command: cp /home/vagrant/networking_ovn/devstack/local.conf.sample /home/vagrant/devstack/local.conf creates=/home/vagrant/devstack/local.conf

- hosts: devstack-compute-1
  tasks:
     - name: create initial local.conf
       command: cp /home/vagrant/networking_ovn/devstack/computenode-local.conf.sample /home/vagrant/devstack/local.conf creates=/home/vagrant/devstack/local.conf

- hosts: devstack-compute-2
  tasks:
     - name: create initial local.conf
       command: cp /home/vagrant/networking_ovn/devstack/computenode-local.conf.sample /home/vagrant/devstack/local.conf creates=/home/vagrant/devstack/local.conf
